### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [mrmekon/connectr#12]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by mrmekon** [comment]
@dtolnay I doubt it, but won't know until I try.  The deprecation announcement came a bit after I started so I stuck with it for now, but I'll try switching to Serde soon.  Thanks for the heads up!
