### ISSUE TITLE
Install fails due to dependency `rustfm-scorbble`

### ISSUE THREAD

**Issue by kloudwrangler** [mrmekon/connectr#43]
I tried to install this application on macOS 11.4 but got the following after running `cargo run`:
```txt
    Updating crates.io index
error: failed to get `rustfm-scrobble` as a dependency of package `connectr v1.1.3-rc (/Users/myuser/src/connectr)`

Caused by:
  failed to load source for dependency `rustfm-scrobble`

Caused by:
  Unable to update /Users/aldoperez/src/connectr/deps/rustfm-scrobble

Caused by:
  failed to read `/Users/aldoperez/src/connectr/deps/rustfm-scrobble/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**Comment by kelna** [comment]
[For some reason] you have to manually download the contents of the rustfm and systray folders in the deps folder. After this, installation finishes OK.

**Comment by mrmekon** [comment]
Yes, you should clone the repo with `git clone --recursive ...` or run `git submodule update --init --recursive` in the directory if you did not initially clone recursively.

GitHub automatically generates source code tarballs on the releases, which do not include submodules so they aren't actually able to build.  I'm not sure if there's any way to fix that.
